postgres:
  image: postgres:9.4
  ports:
    - "5432"
worker:
  build: .
  command: rake jobs:work NEW_RELIC_DISPATCHER=delayed_job
  links:
    - postgres
  environment:
    - DOCKER=true

app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
  environment:
    - DOCKER=true
